### ISSUE TITLE
No models of ememy and weapons in Netrisca with RTX Renderer

### ISSUE THREAD

**Issue by phant** [sultim-t/Serious-Engine-RT#13] opened 2022-01-10 19:13 UTC
1) Vulkan renderer 
2) RTX renderer

![SeriousSamTFE_2022_01_09_14_55_25_626](https://user-images.githubusercontent.com/805222/148824305-42020b6c-9031-4116-94b6-0ddd8573a65d.png)

![SeriousSamTFE_2022_01_09_14_54_38_051](https://user-images.githubusercontent.com/805222/148824307-061f5b81-d80f-4aab-b5dd-a54350e7ab9f.png)

**Comment by JG-Adams** [comment] 2022-02-27 23:31
This problem exist, I would love to see it working.

**Comment by sultim-t** [comment] 2022-02-28 06:44
Oof, yeah, the problem is that my renderer doesn't support custom viewports, and rendering Netricsa will require some work to discard denoiser results, so world and Netrucsa are processed separately. It seems tricky, so maybe it'll be fixed with TSE

**Closed by sultim-t** 2022-02-28 06:44 UTC
